version: "3.7"

services:
  django:
    build:
      context: ./django/
      args:
        MODE: production
    environment:
      MODE: production
      NUM_GUNICORN_WORKERS: 4
      STATIC_ROOT: /var/www/digital_signature/static/
      MEDIA_ROOT: /var/www/digital_signature/media/
      LOGS_ROOT: /var/log/digital_signature/
    logging:
      options:
        max-size: 1g
    volumes:
      - static:/var/www/digital_signature/static/
      - media:/var/www/digital_signature/media/
      - logs:/var/log/digital_signature/

volumes:
  static:
  media:
  logs:
