# Generated by Django 4.2.7 on 2023-11-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_address_alter_employee_number_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='number_id',
            field=models.CharField(error_messages={'unique': 'Crachá já registrado'}, max_length=100, unique=True),
        ),
    ]
