# Generated by Django 4.2.7 on 2023-11-27 21:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('cep', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('cellphone', models.CharField(max_length=11)),
                ('telephone', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['-created_at'],
            },
        ),
    ]
