strictness: veryhigh

ignore-patterns:
  - manage.py
  - docker/.*
  - .*/migrations/.*

uses:
  - django

pep8:
  full: true
  options:
    max-line-length: 120

pylint:
  full: true

mccabe:
  disable:
    - MC0001
